import type { Auth } from "firebase-admin/auth";
import type { Firestore } from "firebase-admin/firestore";
import type { SlotPosition } from "../../../client/types/team.js";

export const PLAYERS = [
  {
    playerId: "2544",
    firstName: "LeBron",
    lastName: "James",
    positions: ["SF", "PF"] as SlotPosition[],
    teamId: "lal",
    teamAbbreviation: "LAL",
    headshotUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/2544.png",
    height: "6-9",
    weight: "250",
    jerseyNumber: "23",
    salary: 12000000,
    gamesPlayed: 35,
    averageStats: {
      assists: 6.8,
      blocks: 0.6,
      fantasyPoints: 53.4,
      minutes: 35.2,
      points: 25.3,
      rebounds: 8.1,
      steals: 1.3,
      turnovers: 3.5,
    },
  },
  {
    playerId: "203507",
    firstName: "Giannis",
    lastName: "Antetokounmpo",
    positions: ["PF", "C"] as SlotPosition[],
    teamId: "mil",
    teamAbbreviation: "MIL",
    headshotUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/203507.png",
    height: "6-11",
    weight: "243",
    jerseyNumber: "34",
    salary: 15000000,
    gamesPlayed: 38,
    averageStats: {
      assists: 5.8,
      blocks: 1.4,
      fantasyPoints: 61.2,
      minutes: 34.5,
      points: 31.2,
      rebounds: 11.9,
      steals: 1.1,
      turnovers: 3.8,
    },
  },
  {
    playerId: "1629029",
    firstName: "Luka",
    lastName: "Doncic",
    positions: ["PG", "SG"] as SlotPosition[],
    teamId: "dal",
    teamAbbreviation: "DAL",
    headshotUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629029.png",
    height: "6-7",
    weight: "230",
    jerseyNumber: "77",
    salary: 13000000,
    gamesPlayed: 36,
    averageStats: {
      assists: 8.2,
      blocks: 0.5,
      fantasyPoints: 54.8,
      minutes: 36.8,
      points: 28.5,
      rebounds: 8.3,
      steals: 1.4,
      turnovers: 4.0,
    },
  },
  {
    playerId: "1630162",
    firstName: "Anthony",
    lastName: "Edwards",
    positions: ["SG", "SF"] as SlotPosition[],
    teamId: "min",
    teamAbbreviation: "MIN",
    headshotUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630162.png",
    height: "6-4",
    weight: "225",
    jerseyNumber: "5",
    salary: 10000000,
    gamesPlayed: 37,
    averageStats: {
      assists: 5.1,
      blocks: 0.6,
      fantasyPoints: 45.5,
      minutes: 35.6,
      points: 26.1,
      rebounds: 5.4,
      steals: 1.3,
      turnovers: 3.2,
    },
  },
  {
    playerId: "1628389",
    firstName: "Bam",
    lastName: "Adebayo",
    positions: ["C", "PF"] as SlotPosition[],
    teamId: "mia",
    teamAbbreviation: "MIA",
    headshotUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628389.png",
    height: "6-9",
    weight: "255",
    jerseyNumber: "13",
    salary: 11000000,
    gamesPlayed: 36,
    averageStats: {
      assists: 3.8,
      blocks: 1.1,
      fantasyPoints: 41.7,
      minutes: 33.4,
      points: 18.9,
      rebounds: 10.2,
      steals: 1.2,
      turnovers: 2.5,
    },
  },
  {
    playerId: "201939",
    firstName: "Stephen",
    lastName: "Curry",
    positions: ["PG"] as SlotPosition[],
    teamId: "gsw",
    teamAbbreviation: "GSW",
    headshotUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/201939.png",
    height: "6-2",
    weight: "185",
    jerseyNumber: "30",
    salary: 14000000,
    gamesPlayed: 34,
    averageStats: {
      assists: 6.1,
      blocks: 0.4,
      fantasyPoints: 44.9,
      minutes: 34.1,
      points: 27.8,
      rebounds: 4.5,
      steals: 1.0,
      turnovers: 3.1,
    },
  },
  {
    playerId: "201142",
    firstName: "Kevin",
    lastName: "Durant",
    positions: ["SF", "PF"] as SlotPosition[],
    teamId: "pho",
    teamAbbreviation: "PHX",
    headshotUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/201142.png",
    height: "6-10",
    weight: "240",
    jerseyNumber: "35",
    salary: 14500000,
    gamesPlayed: 33,
    averageStats: {
      assists: 5.4,
      blocks: 1.0,
      fantasyPoints: 47.3,
      minutes: 36.0,
      points: 29.5,
      rebounds: 7.2,
      steals: 0.9,
      turnovers: 3.0,
    },
  },
  {
    playerId: "203954",
    firstName: "Joel",
    lastName: "Embiid",
    positions: ["C", "PF"] as SlotPosition[],
    teamId: "phi",
    teamAbbreviation: "PHI",
    headshotUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/203954.png",
    height: "7-0",
    weight: "280",
    jerseyNumber: "21",
    salary: 15000000,
    gamesPlayed: 32,
    averageStats: {
      assists: 4.2,
      blocks: 1.8,
      fantasyPoints: 56.5,
      minutes: 34.7,
      points: 31.7,
      rebounds: 11.6,
      steals: 1.1,
      turnovers: 3.5,
    },
  },
  {
    playerId: "1628369",
    firstName: "Jayson",
    lastName: "Tatum",
    positions: ["SF", "PF"] as SlotPosition[],
    teamId: "bos",
    teamAbbreviation: "BOS",
    headshotUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628369.png",
    height: "6-8",
    weight: "210",
    jerseyNumber: "0",
    salary: 13500000,
    gamesPlayed: 35,
    averageStats: {
      assists: 4.8,
      blocks: 0.7,
      fantasyPoints: 46.2,
      minutes: 36.2,
      points: 29.1,
      rebounds: 8.0,
      steals: 1.0,
      turnovers: 2.7,
    },
  },
];

export const run = async (db: Firestore, _auth: Auth): Promise<void> => {
  const batch = db.batch();
  for (const player of PLAYERS) {
    batch.set(db.collection("nbaPlayers").doc(player.playerId), player);
  }
  await batch.commit();
  console.log(`Injected ${PLAYERS.length} NBA players`);
};
