name: CI Checks

on:
  push:
  workflow_dispatch:

jobs:
  ci-checks:
    name: CI Checks
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Setup Expo
        working-directory: client
        run: npx expo install

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            client/node_modules
            client/.expo
            ~/.expo
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Check TypeScript
        working-directory: client
        run: npm run tsc

      - name: Run Linting
        working-directory: client
        run: npx eslint .

      - name: Run Tests
        working-directory: client
        run: npm run test-ci
